import React from 'react';
import type { Metadata } from 'next';
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ClientsLayout({ children }: { children: React.ReactNode }) {
  return children;
}
