import './globals.scss';

import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { IChildren } from '@/types';
import Header from '@/components/Header';
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '@/components/footer';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: IChildren) {
  return (
    <html lang="en">
      <body className={`${inter.className} red_color`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
